name: homelab-dev

services:
  whoami:
    image: traefik/whoami:latest
    container_name: homelab-dev-whoami
    restart: unless-stopped
    ports:
      - "8081:80"

  nginx:
    image: nginx:alpine
    container_name: homelab-dev-nginx
    restart: unless-stopped
    ports:
      - "8082:80"
